name: Release

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov
      - name: Lint with checkov
        run: |
          checkov --skip-check CKV_AWS_50 -d modules

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        npm install @semantic-release/commit-analyzer \
                    @semantic-release/release-notes-generator \
                    @semantic-release/github \
                    conventional-changelog-eslint \
                    semantic-release
    - name: Create release
      run: |
        npx semantic-release -e ./.github/.releaserc.json
      env:
        GITHUB_TOKEN: ${{ secrets.CLOUDMITIGATOR_GITHUB_PAT }}
